# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecdcc76a8a9aabab1fb646cb3f442e69ec6b48382e03ad68551b53a9e8042a360e786bdf76a7088ec39edb51a863a828741007c84aedb731cf91cbcb4fff554e

test:
  secret_key_base: e2b694f59687a7921f92d70a6381cdfa4c5220202990a10d0fa7d16a90357ab7240a372112afc505fda4fad3c629cac5d0da0bc4cfacea0b397d119ff324c096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
